module.exports = {
  docs: [
    '00-intro',
    {
      'Módulo 1 - HTML y CSS': [
        'modulo-1/introduccion',
        'modulo-1/proyecto',
        'modulo-1/instrucciones-ejercicios',
        {
          '👩‍💻 Clases': [
            'modulo-1/clase-00',
            'modulo-1/clase-01',
            'modulo-1/clase-02',
            'modulo-1/clase-03',
            'modulo-1/clase-04',
            'modulo-1/clase-05',
            'modulo-1/clase-06',
            'modulo-1/clase-07',
            'modulo-1/clase-08',
            'modulo-1/clase-09',
            'modulo-1/clase-10',
            'modulo-1/clase-11',
            'modulo-1/clase-12',
            'modulo-1/clase-13',
            'modulo-1/clase-14',
            'modulo-1/clase-15',
            'modulo-1/clase-16',
            'modulo-1/clase-17',
            'modulo-1/clase-18',
            'modulo-1/clase-19',
            'modulo-1/clase-20',
            'modulo-1/clase-21',
            'modulo-1/clase-22',
            'modulo-1/clase-23',
            'modulo-1/clase-24',
          ],
        },
      ],
      'Módulo 2 - JavaScript': [
        'modulo-2/introduccion',
        'modulo-2/proyecto',
        {
          '👩‍💻 Clases': [
            'modulo-2/clase-25',
            'modulo-2/clase-26',
            'modulo-2/clase-27',
            'modulo-2/clase-28',
            'modulo-2/clase-29',
            'modulo-2/clase-30',
            'modulo-2/clase-31',
            'modulo-2/clase-32',
            'modulo-2/clase-33',
            'modulo-2/clase-34',
            'modulo-2/clase-35',
            'modulo-2/clase-36',
          ],
        },
      ],
      'Módulo 3 - Algoritmos': [
        'modulo-3/introduccion',
        {
          '👩‍💻 Clases': [
            'modulo-3/clase-37',
            'modulo-3/clase-38',
            'modulo-3/clase-39',
            'modulo-3/clase-40',
            'modulo-3/clase-41',
            'modulo-3/clase-42',
          ],
        },
      ],
      'Módulo 4 - Estructuras de control': [
        'modulo-4/introduccion',
        'modulo-4/proyecto',
        {
          '👩‍💻 Clases': [
            'modulo-4/clase-43',
            'modulo-4/clase-44',
            'modulo-4/clase-45',
            'modulo-4/clase-46',
            'modulo-4/clase-47',
            'modulo-4/clase-48',
            'modulo-4/clase-49',
            'modulo-4/clase-50',
            'modulo-4/clase-51',
            'modulo-4/clase-52',
            'modulo-4/clase-53',
            'modulo-4/clase-54',
          ],
        },
      ],
      'Módulo 5 - Estructuras de datos': [
        'modulo-5/introduccion',
        {
          '👩‍💻 Clases': [
            'modulo-5/clase-55',
            'modulo-5/clase-56',
            'modulo-5/clase-57',
            'modulo-5/clase-58',
            'modulo-5/clase-59',
            'modulo-5/clase-60',
            'modulo-5/clase-61',
            'modulo-5/clase-62',
            'modulo-5/clase-63',
            'modulo-5/clase-64',
            'modulo-5/clase-65',
            'modulo-5/clase-66',
            'modulo-5/clase-67',
            'modulo-5/clase-68',
            'modulo-5/clase-69',
            'modulo-5/clase-70',
            'modulo-5/clase-71',
            'modulo-5/clase-72',
          ],
        },
      ],
    },
  ],
}
