module.exports = {
  docs: {
    Bienvenida: ['00-intro'],
    'Módulo 1 - HTML y CSS': [
      'modulo-1/introduccion',
      'modulo-1/proyecto',
      {
        Clases: [
          'modulo-1/clase-01',
          'modulo-1/clase-02',
          'modulo-1/clase-03',
          'modulo-1/clase-04',
          'modulo-1/clase-05',
          'modulo-1/clase-06',
          'modulo-1/clase-07',
          'modulo-1/clase-08',
          'modulo-1/clase-09',
          'modulo-1/clase-10',
          'modulo-1/clase-11',
          'modulo-1/clase-12',
          'modulo-1/clase-13',
          'modulo-1/clase-14',
          'modulo-1/clase-15',
          'modulo-1/clase-16',
          'modulo-1/clase-17',
          'modulo-1/clase-18',
          'modulo-1/clase-19',
          'modulo-1/clase-20',
          'modulo-1/clase-21',
          'modulo-1/clase-22',
          'modulo-1/clase-23',
          'modulo-1/clase-24',
        ],
      },
    ],
    // 'Módulo 2 - JavaScript': [
    //   'modulo-2/introduccion',
    //   'modulo-2/proyecto',
    //   {
    //     Clases: [
    //       'modulo-2/clase-13',
    //       'modulo-2/clase-14',
    //       'modulo-2/clase-15',
    //       'modulo-2/clase-16',
    //       'modulo-2/clase-17',
    //       'modulo-2/clase-18',
    //       'modulo-2/clase-19',
    //       'modulo-2/clase-20',
    //       'modulo-2/clase-21',
    //       'modulo-2/clase-22',
    //       'modulo-2/clase-23',
    //       'modulo-2/clase-24',
    //       'modulo-2/clase-25',
    //       'modulo-2/clase-26',
    //       'modulo-2/clase-27',
    //       'modulo-2/clase-28',
    //       'modulo-2/clase-29',
    //       'modulo-2/clase-30',
    //     ],
    //   },
    // ],
  },
}
