module.exports = {
  docs: [
    "00-intro",
    {
      "Módulo 1 - HTML y CSS": [
        "modulo-1/introduccion",
        "modulo-1/proyecto",
        "modulo-1/instrucciones-ejercicios",
        {
          "👩‍💻 Clases": [
            "modulo-1/clase-00",
            "modulo-1/clase-01",
            "modulo-1/clase-02",
            "modulo-1/clase-03",
            "modulo-1/clase-04",
            "modulo-1/clase-05",
            "modulo-1/clase-06",
            "modulo-1/clase-07",
            "modulo-1/clase-08",
            "modulo-1/clase-09",
            "modulo-1/clase-10",
            "modulo-1/clase-11",
            "modulo-1/clase-12",
            "modulo-1/clase-13",
            "modulo-1/clase-14",
            "modulo-1/clase-15",
            "modulo-1/clase-16",
            "modulo-1/clase-17",
            "modulo-1/clase-18",
            "modulo-1/clase-19",
            "modulo-1/clase-20",
            "modulo-1/clase-21",
            "modulo-1/clase-22",
            "modulo-1/clase-23",
          ],
        },
      ],
      "Módulo 2 - JavaScript": [
        "modulo-2/introduccion",
        "modulo-2/proyecto",
        {
          "👩‍💻 Clases": [
            "modulo-2/clase-01",
            "modulo-2/clase-02",
            "modulo-2/clase-03",
            "modulo-2/clase-04",
            "modulo-2/clase-05",
            "modulo-2/clase-06",
            "modulo-2/clase-07",
            "modulo-2/clase-08",
            "modulo-2/clase-09",
            "modulo-2/clase-10",
            "modulo-2/clase-11",
            "modulo-2/clase-12",
          ],
        },
      ],
      "Módulo 3 - Estructuras de datos": [
        "modulo-3/introduccion",
        "modulo-3/proyecto",
        {
          "👩‍💻 Clases": [
            "modulo-3/clase-01",
            "modulo-3/clase-02",
            "modulo-3/clase-03",
            "modulo-3/clase-04",
            "modulo-3/clase-05",
            "modulo-3/clase-06",
            "modulo-3/clase-07",
            "modulo-3/clase-08",
            "modulo-3/clase-09",
            "modulo-3/clase-10",
            "modulo-3/clase-11",
            "modulo-3/clase-12",
            "modulo-3/clase-13",
            "modulo-3/clase-14",
            "modulo-3/clase-15",
            "modulo-3/clase-16",
            "modulo-3/clase-17",
            "modulo-3/clase-18",
            "modulo-3/clase-19",
            "modulo-3/clase-20",
          ],
        },
      ],
      "Módulo 4 - Asincronismo": [
        "modulo-4/introduccion",
        "modulo-4/proyecto",
        {
          "👩‍💻 Clases": [
            "modulo-4/clase-01",
            "modulo-4/clase-02",
            "modulo-4/clase-03",
            "modulo-4/clase-04",
            "modulo-4/clase-05",
            "modulo-4/clase-06",
            "modulo-4/clase-07",
            "modulo-4/clase-08",
          ],
        },
      ],
      "Módulo 5 - React": [
        "modulo-5/introduccion",
        "modulo-5/proyecto",
        {
          "👩‍💻 Clases": [
            "modulo-5/clase-01",
            "modulo-5/clase-02",
            "modulo-5/clase-03",
            "modulo-5/clase-04",
            "modulo-5/clase-05",
            "modulo-5/clase-06",
            "modulo-5/clase-07",
            "modulo-5/clase-08",
            "modulo-5/clase-09",
            "modulo-5/clase-10",
            "modulo-5/clase-11",
            "modulo-5/clase-12",
            "modulo-5/clase-13",
            "modulo-5/clase-14",
            "modulo-5/clase-15",
            "modulo-5/clase-16",
            "modulo-5/clase-17",
            "modulo-5/clase-18",
          ],
        },
      ],
      "Módulo 6 - Aplicaciones de página única": [
        "modulo-6/introduccion",
        "modulo-6/proyecto",
        {
          "👩‍💻 Clases": [
            "modulo-6/clase-01",
            "modulo-6/clase-02",
            "modulo-6/clase-03",
            "modulo-6/clase-04",
            "modulo-6/clase-05",
            "modulo-6/clase-06",
            "modulo-6/clase-07",
            "modulo-6/clase-08",
            "modulo-6/clase-09",
            "modulo-6/clase-10",
            "modulo-6/clase-11",
            "modulo-6/clase-12",
            "modulo-6/clase-13",
            "modulo-6/clase-14",
            "modulo-6/clase-15",
            "modulo-6/clase-16",
            "modulo-6/clase-17",
            "modulo-6/clase-18",
          ],
        },
      ],
      // 'Módulo 7 - React': [
      //   'modulo-7/introduccion',
      //   {
      //     '👩‍💻 Clases': [
      //       'modulo-7/clase-88',
      //       'modulo-7/clase-89',
      //       'modulo-7/clase-90',
      //       'modulo-7/clase-91',
      //       'modulo-7/clase-92',
      //       'modulo-7/clase-93',
      //       'modulo-7/clase-94',
      //       'modulo-7/clase-95',
      //       'modulo-7/clase-96',
      //       'modulo-7/clase-97',
      //       'modulo-7/clase-98',
      //       'modulo-7/clase-99',
      //       'modulo-7/clase-100',
      //       'modulo-7/clase-101',
      //       'modulo-7/clase-102',
      //       'modulo-7/clase-103',
      //       'modulo-7/clase-104',
      //       'modulo-7/clase-105',
      //     ],
      //   },
      // ],
      // 'Módulo 8 - Aplicaciones de página única': [
      //   'modulo-8/introduccion',
      //   'modulo-8/proyecto',
      //   {
      //     '👩‍💻 Clases': [
      //       'modulo-8/clase-106',
      //       'modulo-8/clase-107',
      //       'modulo-8/clase-108',
      //       'modulo-8/clase-109',
      //       'modulo-8/clase-110',
      //       'modulo-8/clase-111',
      //       'modulo-8/clase-112',
      //       'modulo-8/clase-113',
      //       'modulo-8/clase-114',
      //       'modulo-8/clase-115',
      //       'modulo-8/clase-116',
      //       'modulo-8/clase-117',
      //       'modulo-8/clase-118',
      //       'modulo-8/clase-119',
      //       'modulo-8/clase-120',
      //       'modulo-8/clase-121',
      //       'modulo-8/clase-122',
      //       'modulo-8/clase-123',
      //     ],
      //   },
      // ],
    },
  ],
};
